name: Build sing-box rule-set

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download GeoHideDNS hosts
        run: |
          curl -L \
          https://raw.githubusercontent.com/Internet-Helper/GeoHideDNS/main/hosts/hosts \
          -o hosts

      - name: Install sing-box
        run: |
          wget -q \
          https://github.com/SagerNet/sing-box/releases/download/v1.13.14/sing-box-1.13.14-linux-amd64.tar.gz

          tar xf sing-box-1.13.14-linux-amd64.tar.gz

          sudo mv \
          sing-box-1.13.14-linux-amd64/sing-box \
          /usr/local/bin/sing-box

          sing-box version

      - name: Convert hosts to rule-set
        run: |
          bash scripts/convert.sh

      - name: Delete old release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest \
          --yes \
          --cleanup-tag || true

      - name: Create new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create latest \
          geohide.srs \
          --title "GeoHideDNS sing-box rules" \
          --notes "Automatic update"